### ISSUE TITLE
Google Play - Sign in

### ISSUE THREAD

**Issue by acamenhas** [CodesFirst/new_version_plus#14]
Hi all,

I've installed this plugin and when I press to update the app it goes to the Google Play app page (ok) but the green button says: "Install" and then when I press it it shows a popup saying to sign in...

Anyone have this behaviour?

Thanks

**Comment by acamenhas** [comment]
It seams like a different country page of the Google Play app.

In my case my app is in Portuguese, I've installed in Portuguese and the link of the plugin goes to a English version.

**Comment by acamenhas** [comment]
I think the plugin must give the same possibility to choose the country code in Android:

final uri = Uri.https("play.google.com", "/store/apps/details",
        {"id": id.toString(), "hl": "en_US"});

At this time it's forcing en_US.

Can you solve this ASAP?

**Comment by j-j-gajjar** [comment]
in  `pubspec.yaml`

```
  new_version_plus: 
    git:
      url: https://github.com/CodesFirst/new_version_plus.git
      ref: master
```
      
`open dialog code`


```
newVersion.showAlertIfNecessary(
            context: context,
            launchModeVersion: Platform.isAndroid
                ? LaunchModeVersion.external
                : LaunchModeVersion.normal,
          );
```

**Comment by acamenhas** [comment]
Hi, now it works well, thank you!!

An last thing: in your code `newVersion.showAlertIfNecessary(...` how can I do to translate the message, buttons text, etc?

**Comment by j-j-gajjar** [comment]
you can use `showUpdateDialog` for custom button text 
with  this params `launchMode:LaunchMode.externalApplication`
