### ISSUE TITLE
The method '[]' was called on null.

### ISSUE THREAD

**Issue by simariyaketan** [CodesFirst/new_version_plus#15]

**Comment by FCE-tc** [comment]
Looks like Google has changed something on their end. I'm getting the same issue with new_version package....

**Comment by Infinil** [comment]
same here..

**Comment by anhquangdev** [comment]
Same here

**Comment by anhquangdev** [comment]
I am also facing same issue

<img width="711" alt="Screenshot 2023-01-06 at 10 34 43" src="https://user-images.githubusercontent.com/107027297/210924824-a0b0b260-a52e-4dd6-9f40-b261677f6aa5.png">

**Comment by pewiher** [comment]
Hello how are you, good afternoon, the test was carried out and it was satisfactory, could you help me with its implementation, additional.

Remember that the appID must exist in the playstore

**Comment by chitraarasu** [comment]
Ok, now the latest version works for me. But the package prints a complete HTML Play Store response in the console so please fix that.

**Comment by pewiher** [comment]
> 

Ok, remove prints a complete HTML Play Store response in the console
