### ISSUE TITLE
Android Link not opening Play Store App instead opens in fresh WebView

### ISSUE THREAD

**Issue by J-Sizzle** [CodesFirst/new_version_plus#16]
Idk if others are running into this but since it is a fresh webview, the user would need to login to their google account before they could update.

The library creates an app link of this format: `https://play.google.com/store/apps/details?id=$appId&hl=en_US` which opens Webview but I found that this format opens the Play Store app as i would expect: `market://details?id=$appId`

**Comment by pewiher** [comment]
Hello how are you, for this you can use the LaunchMode Version parameter. Additionally, use androidPlayStoreCountry to set the country code.

LaunchModeVersion -> normal or external

`final newVersion = NewVersionPlus(
        iOSId: 'com.google.Vespa',
        androidId: 'com.disney.disneyplus',
        androidPlayStoreCountry: "es_ES" //support country code
        );`

**Comment by J-Sizzle** [comment]
Thanks the LaunchMode worked, sorry i missed that.
