### ISSUE TITLE
Make VersionStatus constructor public for testing

### ISSUE THREAD

**Issue by ernestoA92** [CodesFirst/new_version_plus#19]
For testing this package using Mockito it should be helpful to have VersionStatus constructor public so we can make:

```
when(newVersionMock.getVersionStatus()).thenAnswer(
        (_) => Future.value(
          VersionStatus(
            localVersion: '1.0.0',
            storeVersion: '1.0.1',
            appStoreLink: 'some link',
          ),
        ),
      );
```

This way we can have widget test to check if our app behaves right for all the possible cases.

**Comment by pewiher** [comment]
Done, we will take into account your requirement in future versions, we hope to add it.

Thank you very much for your feedback.

**Comment by pewiher** [comment]
Hello good afternoon, the request was added, it will be available in the new version
