### ISSUE TITLE
It would be nice to be able to pass a barrierDismissal parameter to showUpdateDialog as opposed to it taking the allowDismissal value.

### ISSUE THREAD

**Issue by ChrisMICDUP** [CodesFirst/new_version_plus#23]
I want to allow the dialog to be dismissed, but not by clicking anywhere so I can be assured the user has read the upgrade dialog text

**Comment by pewiher** [comment]
Hello good afternoon, this option is added, the field is: allowDismissal, it is a bool

**Comment by pewiher** [comment]
Hello good afternoon, this option is added, the field is: allowDismissal, it is a bool, it is added in the showUpdateDialog method
