### ISSUE TITLE
Release notes on android appears in single line only

### ISSUE THREAD

**Issue by shalikhshab00** [CodesFirst/new_version_plus#24]
On Android, the release notes are all set as a single line. But on the developer page, it is set as multiline. It also shows HTML tags too.

How can I make release notes on android similar to the ones on ios?

<img width="405" alt="Screenshot 2023-03-31 at 1 49 39 PM" src="https://user-images.githubusercontent.com/57778554/229065821-2ea216cb-fe2a-4d20-b23d-07fca7f06f35.png">

**Comment by pewiher** [comment]
The tests were carried out with some apps and they work correctly if they could add logs or some detail to have better visibility.

**Comment by pewiher** [comment]
Available in the next package update, planned for the 15th of this month.

**Comment by pewiher** [comment]
variable use androidHtmlReleaseNotes (bool) default false
