### ISSUE TITLE
displaying the google play store with the .showUpdateDialog() 

### ISSUE THREAD

**Issue by candrabisa** [CodesFirst/new_version_plus#26]
the problem when displaying the google play store with the .showUpdateDialog() method does not go to the application store on the device instead like a webview. suggestion to make launchModeVersion: LaunchModeVersion.external like .showAlertIfNecessary()

**Comment by pewiher** [comment]
Hello, good afternoon, the showUpdateDialog method has a parameter called launchMode, you can use this parameter to add the LaunchModeVersion.external

**Comment by pewiher** [comment]
Hello good afternoon, the request was added, it will be available in the new version
