### ISSUE TITLE
upgrade http dependency

### ISSUE THREAD

**Issue by triay0** [CodesFirst/new_version_plus#31]
Please upgrade http dependency version to 1.0.0

Error:
Because new_version_plus >=0.0.10 depends on http ^0.13.6 and new_version_plus <0.0.10 depends on http ^0.13.5, every version of new_version_plus requires http ^0.13.5.
So, because [my_app_package] depends on both http ^1.0.0 and new_version_plus ^0.0.9, version solving failed.

Thanks

**Comment by srcho** [comment]
same issue. latest version is 1.1.0

**Comment by pewiher** [comment]
Hi, package http update from 0.13.6 to  1.1.0.

Available in the next package update, planned for the 15th of this month.
