### ISSUE TITLE
net::ERR_UNKNOWN_URL_SCHEME when going to play store page

### ISSUE THREAD

**Issue by BenVercammen** [CodesFirst/new_version_plus#38]
When a user clicks on the "update" button, he is sent to the correct store page, but after a fraction of a second he'll be redirected, resulting in the following error:

**Webpage not available**
The webpage at intent://play.google.com/store/apps/details?id=...&hl=en_US&pcampaignid=web_auto_redirect#Intent;scheme=https;action=android.... could not be loaded because:
net::ERR_UNKNOWN_URL_SCHEME

To illustrate, I've attached a GIF of what happens:

![intent_issue](https://github.com/CodesFirst/new_version_plus/assets/243759/5a5dfd1c-8328-426c-8119-3d0cc33025e3)

This is recorded in an emulator, but the issue was brought to my attention by a user that couldn't update the app.
Also, please don't mind the 0.4.7 to 0.4.6 update, this is me forcing the update dialog...

With regards to troubleshooting, I've upgraded the following packages:

- new_version_plus: from 0.0.9 to 0.0.11
- http: from 0.13.3 to 1.1.0
- url_launcher: from 6.1.10 to 6.1.14

I'm actually thinking that it is an issue on the play store page itself, because of the redirect that's happening, but maybe there are some extra request parameters passed along that trigger this behaviour?

Also, when I hit the device's back button, I get the store page for a fraction of a second before getting the "not available" page again..

Not sure if it is related to **new_version_plus**, but any help would be greatly appreciated!

**Comment by mrcsh** [comment]
I was able to get it to work by adding an intent filter in the AndroidManifest.xml
```
         <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                 <data
                    android:host="play.google.com"
                    android:scheme="intent" />
          </intent-filter>
```

**Comment by BenVercammen** [comment]
Do I add the `intent-filter` inside my  `<activity android:name=".MainActivity" />` element? I've tried a couple of different setups, but I still have the same problem. Would you mind sharing a bit more of your **AndroidManifest.xml**?

**Comment by mrcsh** [comment]
Yes, it's inside the .MainActivty, There was already another entry under <queries> that was added a while ago, maybe both are needed?

```

**Comment by BenVercammen** [comment]
You might be on to something!

I had these queries:

```xml
    <!-- In order to open URL's -->
    <!-- Starting from API 30 Android requires package visibility configuration in your AndroidManifest.xml -->
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data/>
        </intent>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
        <!-- If your app checks for SMS support -->
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="sms" />
        </intent>
        <!-- If your app checks for call support -->
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="tel" />
        </intent>
    </queries>
```
Adding the `intent scheme` did not help however... Might be some other combination with category or something like that. I'll need to take a closer look at it ...

Thanks for the quick replies though!

**Comment by schricb** [comment]
The problem is with url_launcher. This is fixed in the latest Flutter version or for a quick workaround use LaunchModeVersion.external.

**Comment by Ngochiendev** [comment]
> The problem is with url_launcher. This is fixed in the latest Flutter version or for a quick workaround use LaunchModeVersion.external.

did you find the solution, i am getting error with same condition

**Comment by BenVercammen** [comment]
I've tried using `LaunchModeVersion.external`, but it gives the user 2 options (the app itself or a pre-installed browser). When using the browser, things are okay, but when using the app itself, nothing happens anymore. So it's not really a complete solution to my situation, unless I could somehow remove the app itself from the options.

The main problem still seems to be that `Android WebView` is for some reason doing a redirect when opening the URL...

**Comment by BenVercammen** [comment]
Okay, checked the internet some more, and found out that upgrading to a higher version of `url_launcher_android` might be an option. However, when doing so, it just behaves as if I'd use `LaunchModeVersion.external` (while I've got it set explicitly to `normal`).

Sources:
 - https://stackoverflow.com/questions/55706054/unable-to-open-google-play-store-from-android-webview
 - https://github.com/flutter/flutter/issues/106331

**Comment by BenVercammen** [comment]
Some further investation:
 - url_launcher_android: 6.0.39 still opens in WebView, which will redirect
 - url_launcher_android: 6.1.0 opens in external browser without asking to choose an option

So, even though I liked WebView for opening pages inside the app, which url_launcher doesn't do anymore, at least at the moment users don't end up on an error page when looking for an update...

One more funny thing, when debugging `url_launcher_android`, it actually calls `_hostApi.openUrlInWebView`, but still the store page opens in an external browser (other URL's as well).

**Comment by BenVercammen** [comment]
Okay, I finally figured it out!

- Upgraded to latest `url_launcher` and `url_launcher_android` versions
- Upgraded `environment.sdk` from `>=2.17.0 <3.0.0` to `>=3.2.0-134.1.beta <4.0.0`
- No need for extra `intent-filters` for `play.google.com`
- The following config is required:
```xml
    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="https" />
        </intent>
    </queries>
```

It was when setting up a minimal project to report a bug to `url_launcher` that I stumbled upon the fact that my `environment.sdk` was a bit outdated...


So in the end, it had nothing to do with `new_version_plus`, but was more related to `url_launcher`, or so I guess. Still the redirect on the webpage remains a bit weird...
