### ISSUE TITLE
Update package_info_plus version up to 5.x.x

### ISSUE THREAD

**Issue by TatsuUkraine** [CodesFirst/new_version_plus#39]
The current version of the package uses package_info_plus v4

**Comment by TatsuUkraine** [comment]
any update on this? is this package still maintained?

**Comment by gerken-tss** [comment]
I have forked the package. For now, you can do this in your `pubspec.yaml`:

```
  new_version_plus:
    git:
      url: https://github.com/gerken-tss/new_version_plus
```

**Comment by matteoberla** [comment]
Hopefully the owner will make this minor update

**Comment by pewiher** [comment]
thank you it will be included in the new version of the package
