### ISSUE TITLE
why this package return local and store version 0.0.0

### ISSUE THREAD

**Issue by expertdev-designer** [CodesFirst/new_version_plus#5]
I/flutter (11162): StoreCheckVersion Bug Fixes and Enhancements
I/flutter (11162): status https://play.google.com/store/apps/details?id=com.saudia.umrah&hl=en
I/flutter (11162): localVersion status 0.0.0
I/flutter (11162): canUpdate false
I/flutter (11162): storeVersion status 0.0.0

**Comment by pewiher** [comment]
Update version 0.0.4, thanks [mauriziopinotti](https://github.com/mauriziopinotti)
