### ISSUE TITLE
Upgrade package_info_plus

### ISSUE THREAD

**Issue by alexaungmyooo** [CodesFirst/new_version_plus#51]
new_version_plus ^0.0.11 which depends on package_info_plus ^4.0.2, package_info_plus ^4.0.2 is required.

**Comment by alexaungmyooo** [comment]
I think this guys does not support this package anymore.

**Comment by zakblacki** [comment]
still waiting

**Comment by pewiher** [comment]
thanks for the pr, will be in the new version
