### ISSUE TITLE
Error resolving dependencies after updating package_info_plus to 2.0.0

### ISSUE THREAD

**Issue by hugovangalen** [CodesFirst/new_version_plus#7]
I took new_version_plus for a whirl because new_version development stopped and I received an error while that was resolving dependencies. I am however, receiving the same error with this package.

The error is:

```
Because new_version_plus >=0.0.2 depends on package_info_plus ^1.4.3+1 and (project) depends on package_info_plus ^2.0.0, new_version_plus >=0.0.2 is forbidden.
So, because (project) depends on new_version_plus ^0.0.3, version solving failed.
```

**Comment by pewiher** [comment]
update in the version 0.0.4, thanks [Polevshchikov](https://github.com/Polevshchikov)
